//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace WebApplication1.ePx_ECM
{

    public partial class WFM_USER_SISTEMA : XPLiteObject
    {
        string fUSR_TIPIDE;
        [Size(4)]
        public string USR_TIPIDE
        {
            get { return fUSR_TIPIDE; }
            set { SetPropertyValue<string>(nameof(USR_TIPIDE), ref fUSR_TIPIDE, value); }
        }
        string fUSR_ID;
        [Key]
        [Size(15)]
        public string USR_ID
        {
            get { return fUSR_ID; }
            set { SetPropertyValue<string>(nameof(USR_ID), ref fUSR_ID, value); }
        }
        string fUSR_USER;
        [Size(50)]
        public string USR_USER
        {
            get { return fUSR_USER; }
            set { SetPropertyValue<string>(nameof(USR_USER), ref fUSR_USER, value); }
        }
        string fUSR_PWD;
        public string USR_PWD
        {
            get { return fUSR_PWD; }
            set { SetPropertyValue<string>(nameof(USR_PWD), ref fUSR_PWD, value); }
        }
        int fUSR_PWD_EXP;
        public int USR_PWD_EXP
        {
            get { return fUSR_PWD_EXP; }
            set { SetPropertyValue<int>(nameof(USR_PWD_EXP), ref fUSR_PWD_EXP, value); }
        }
        DateTime fUSR_FECHA_CAMBIO_PWD;
        public DateTime USR_FECHA_CAMBIO_PWD
        {
            get { return fUSR_FECHA_CAMBIO_PWD; }
            set { SetPropertyValue<DateTime>(nameof(USR_FECHA_CAMBIO_PWD), ref fUSR_FECHA_CAMBIO_PWD, value); }
        }
        decimal fUSR_INTENTOS_LOGUEO;
        public decimal USR_INTENTOS_LOGUEO
        {
            get { return fUSR_INTENTOS_LOGUEO; }
            set { SetPropertyValue<decimal>(nameof(USR_INTENTOS_LOGUEO), ref fUSR_INTENTOS_LOGUEO, value); }
        }
    }

}
